### ISSUE TITLE
GLES: Unable to create a GL context

### ISSUE THREAD

**Issue by CalcProgrammer1** [Rafostar/clapper#215] opened 2022-02-11 01:28 UTC
I installed Clapper via AUR (both clapper and clapper-git, which builds from git) on my PinePhone with Manjaro.  I can play videos using gst-play-1.0 --use-playbin3 but not with Clapper, as opening it shows the error "Unable to create a GL context".  I have tested other OpenGL apps (glxgears, glxinfo) and GL is working so I'm not sure why I'm seeing this error.  I tried on my PinePhone Pro as well and it works fine.  For reference, gstreamer 1.20 landed in Manjaro's repos today so I was testing hardware accelerated playback.

**Comment by Rafostar** [comment] 2022-02-11 08:18
That's a GTK 4.6.0 problem. It seems to fail with OpenGL ES. Trying `gtk4-demo --run=gears` gives the same problem. Downgrading to GTK 4.4.1 and it works correctly again.

**Comment by Rafostar** [comment] 2022-02-12 17:28
I cannot move issues from github to gitlab. Please open this on GTK gitlab instead. As I mentioned earlier `gtk4-demo --run=gears` is a good way to reproduce this for them without installing Clapper. The problem is that OpenGL ES does not work anymore in GTK 4.6, where it worked fine in 4.4.

**Comment by Aurnytoraink** [comment] 2022-02-15 08:25
It seems to be solved in GTK 4.6.1

![image](https://user-images.githubusercontent.com/28545669/154021663-4d71c320-b44e-41dc-9cd0-5a6850e0b499.png)

**Comment by Rafostar** [comment] 2022-02-15 09:06
@Aurnytoraink 

Not sure what kind of HW you have tested this with, as OpenGL ES is right now used only as fallback for devices that do not have new enough version of OpenGL like Pinephone mentioned by OP.
```sh
MESA_GL_VERSION_OVERRIDE=2.1 GDK_DEBUG=opengl gtk4-demo --run=gears
```
Gives me legacy OpenGL 2.1 instead of OpenGL ES even with 4.6.1, while it works fine on 4.4 series. AFAIK default expected order of GTK4 should be: OpenGL -> GLES -> legacy OpenGL.

I was hoping that this can be worked around with newly introduced `gdk_gl_context_set_allowed_apis` function in GTK4 to do the requests one by one of preferred by app order of GL contexts myself. Sadly this new API does not seem to work either. For this one I have opened a bug myself: https://gitlab.gnome.org/GNOME/gtk/-/issues/4697. This is related but different issue. For the bug of auto fallback to GLES no longer working on devices like Pinephone, someone with such device (where this can be tested reliably) should probably open another issue.

**Comment by Rafostar** [comment] 2022-02-15 15:05
As a workaround, to force GL ES with gtk 4.6.1, one can use `MESA_GL_VERSION_OVERRIDE=1.0`. This should also improve performance on your PinePhone Pro.

**Comment by Rafostar** [comment] 2022-02-16 09:22
GTK devs say that this behavior change is intentional, now app needs to request GL/GLES with newly introduced API that ATM still does not work as expected :man_shrugging: . Guess this gonna need fixes to GTK4 to get it working on their side and manually requesting GLES here.

Still `MESA_GL_VERSION_OVERRIDE=1.0` workaround seems to work for now and downgrading into GTK 4.4 works too. As usual Flatpak version of Clapper ships carefully chosen (tested by me) versions of underlying libs, so also works without problems.

**Comment by Rafostar** [comment] 2022-05-10 10:51
The new Clapper sink that is capable of automatically requesting GLES was merged recently. The rest needs to be fixed on the GTK4 side now. Here is the link to current work on fixing this on their side: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4687

Nothing more at the moment to fix on my side of things, rest remains to the GTK4 devs, so closing.

**Closed by Rafostar** 2022-05-10 10:51 UTC
Labels: GTK 4.6
