### ISSUE TITLE
Floating window shrinks if dragged during reveal controls animation

### ISSUE THREAD

**Issue by tabzlock** [Rafostar/clapper#48] opened 2021-03-01 09:02 UTC
When exiting floating mode the window will shrink a small amount if moved. This continues to stack until you get a tiny window.

Before:
![image](https://user-images.githubusercontent.com/65925392/109473659-4f237c80-7abf-11eb-82a7-b56a19dd8101.png)
After:
![image](https://user-images.githubusercontent.com/65925392/109473738-6d897800-7abf-11eb-9b13-7c2f1dddd88f.png)

replicating issue:

https://user-images.githubusercontent.com/65925392/109474778-965e3d00-7ac0-11eb-9219-2b755872d524.mp4

**Comment by Rafostar** [comment] 2021-03-01 09:17
> When exiting floating mode the window will shrink a small amount if moved.

What GNOME Shell version is this? Does this also happen if you drag after animation finishes?

**Comment by laurinneff** [comment] 2021-03-01 09:27
This happens to me as well. I'm on GNOME 3.38.4, and it doesn't happen after the animation is finished.

**Comment by tabzlock** [comment] 2021-03-01 09:28
> This happens to me as well. I'm on GNOME 3.38.4, and it doesn't happen after the animation is finished.

exactly the same for me

**Comment by Rafostar** [comment] 2021-03-01 09:40
I cannot reproduce this currently. Let me just make sure of one thing here. Even if you trigger floating/normal window multiple times without drag or drag after animation then there is no size change, yes?

**Comment by Rafostar** [comment] 2021-03-01 10:10
Ah. I was finally able to reproduce. But only on X11. Does not happen on Wayland to me.

**Comment by Rafostar** [comment] 2021-03-01 17:18
This seems like a `mutter` bug to me. Especially considering that it also changes width on its own.

For now I have opened this as an issue on `mutter` gitlab:
[https://gitlab.gnome.org/GNOME/mutter/-/issues/1674](https://gitlab.gnome.org/GNOME/mutter/-/issues/1674)

**Comment by tabzlock** [comment] 2021-03-25 07:23
still happens in gnome 40 on fedora 34.

**Comment by Rafostar** [comment] 2021-03-25 09:30
@tabzlock 

Please see the `mutter` issue I opened:
[https://gitlab.gnome.org/GNOME/mutter/-/issues/1674](https://gitlab.gnome.org/GNOME/mutter/-/issues/1674)

> still happens in gnome 40 on fedora 34.

This is a `mutter` bug, not Clapper fault. You have to wait patiently until the issue I linked is resolved. They are working on it :-)

I just left this issue opened, so other people that have this "inconvenience" can know what causes this and won't keep opening similar issues in Clapper github.

**Comment by Rafostar** [comment] 2021-04-18 17:06
Now fixed in `mutter`.

**Closed by Rafostar** 2021-04-18 17:06 UTC
Labels: not my bug
