### ISSUE TITLE
Controlling playback speed 

### ISSUE THREAD

**Issue by blaze1522** [Rafostar/clapper#271] opened 2022-05-31 05:23 UTC

**Comment by sp1ritCS** [comment] 2022-05-31 06:08
you can change the playback speed by clicking on the time indicator. that should open a popup with a slider for it.

**Comment by Rafostar** [comment] 2022-05-31 06:30
Maybe if I add screenshot of it to readme, it will be easier to find. Anyway as mentioned above, the feature is already available. Just click on the elapsed time to see it.

**Comment by Rafostar** [comment] 2022-05-31 06:30
Duplicate of #33

**Closed** 2022-05-31 06:30 UTC
