### ISSUE TITLE
Use AdwPreferences

### ISSUE THREAD

**Issue by SeaDve** [Rafostar/clapper#84] opened 2021-06-17 12:47 UTC
Also similar with other modern version of gnome apps like nautilus and epiphany

**Comment by Rafostar** [comment] 2021-06-17 13:09
This is a duplicate of #67 

Please see my response in that thread why no `libadwaita` yet.

**Closed by Rafostar** 2021-06-17 13:09 UTC

**Comment by SeaDve** [comment] 2021-06-17 13:15
i see, thanks!
