### ISSUE TITLE
Jagged text in the UI

### ISSUE THREAD

**Issue by pedrofleck** [Rafostar/clapper#56] opened 2021-03-25 04:19 UTC
I installed Clapper on a fresh install of Fedora 34 Beta (with Gnome 40) and the text doesn't seem to be hinted/anti-aliased. It appears that the subtitles are not hinted either, but I'm not sure because it's harder to notice with larger text (plus the black borders). This didn't happen when I had an older version of Clapper on my Fedora 33 install. This isn't happening with any other app (including GTK4 ones). I installed the Flathub version.
![Captura de tela de 2021-03-24 21-13-29](https://user-images.githubusercontent.com/761321/112417943-524d0980-8d07-11eb-813c-e6b49fc9d837.png)

**Comment by Rafostar** [comment] 2021-03-25 08:07
All those text labels in that menu are auto-generated from single `.ui` file: [https://github.com/Rafostar/clapper/blob/master/ui/clapper.ui](https://github.com/Rafostar/clapper/blob/master/ui/clapper.ui). As you can see there is absolutely no scaling/hinting code in the Clapper itself (same goes for elapsed video time button on bottom).

One of the underlying libraries used by this app must be misbehaving. Normally I would say `pango` fault (if subtitles are also affected), but considering you use Flatpak version, we both have the same `pango` ver that is included in Flathub, so it might be a `mesa` bug. I personally am using Fedora 33 with both Flathub version (for daily use) and a local installation in toolbox for development and I cannot reproduce this issue in neither of them.

**Comment by Rafostar** [comment] 2021-03-25 09:01
@pedrofleck 

I just found this issue on flatpak:
[https://github.com/flatpak/flatpak/issues/2861](https://github.com/flatpak/flatpak/issues/2861)

Does this look like what you are experiencing?

**Comment by pedrofleck** [comment] 2021-03-25 16:37
Hi @Rafostar, thanks for the fast response!

About this issue on flatpak, it looks to be the same issue visually, but I don't have this issue with any other flatpak apps (including GTK4 ones).

Is there a way to check if it is related to Mesa? I think I have Mesa 20.0.X, but I can confirm later when I get back to my laptop. I'll also try to reduce the subtitle font size to check if is just the UI or not.

**Comment by Rafostar** [comment] 2021-03-25 17:27
> but I don't have it with any other flatpak apps (including GTK4 ones).

If it does not happen with other flatpak GTK4 apps, then this might be a different issue. Right now GTK4 is not included in flatpak runtime, so all apps are including it with themselves. The version included right now in Clapper is 4.1.1.

> This didn't happen when I had an older version of Clapper on my Fedora 33 install.

I am updating the included GTK4 version from time to time, so it might be a bug in recent GTK4, but I cannot tell for sure since you also changed your OS. I do not have this issue on my Fedora 33 system through.

Do you have any warnings printed when you start Clapper from terminal?
```sh
flatpak run com.github.rafostar.Clapper
```

**Comment by pedrofleck** [comment] 2021-03-25 18:31
> If it does not happen with other flatpak GTK4 apps, then this might be a different issue. Right now GTK4 is not included in flatpak runtime, so all apps are including it with themselves. The version included right now in Clapper is 4.1.1.

Doesn't Gnome 40's runtime include GTK4? I have it installed. But now I'm not sure if I have any other GTK4 on flatpak, I thought [Blanket](https://github.com/rafaelmardojai/blanket) was one of them, because it has the rounded corners in every corner of the window, but I checked its repo and it seems like it's still GTK3. Do you have any suggestion of a flatpak GTK4 application that I can install without having to enable Flathub testing repo?

> Do you have any warnings printed when you start Clapper from terminal?

No, it doesn't show any warning or message.

**Comment by Rafostar** [comment] 2021-03-25 19:31
> Doesn't Gnome 40's runtime include GTK4?

Maybe, but we are using 3.38 ATM.

> was one of them, because it has the rounded corners in every corner of the window

Shocking revelation for you then: GTK4 does NOT have rounded corners yet :-) I had to enforce them for Clapper, in order to avoid a situation where floating mode (PiP) video has only top corners rounded. It would look weird like that.

> without having to enable Flathub testing repo?

Actually, since the GTK4 version in Clapper is a debug build it has one GTK4 application that is not part of Clapper. Its `GTK Inspector` (used for debugging). You can try it if you want see a non-clapper app without installing anything.

```sh
GTK_DEBUG=interactive flatpak run com.github.rafostar.Clapper
```

**Comment by pedrofleck** [comment] 2021-03-26 01:13
> Shocking revelation for you then: GTK4 does NOT have rounded corners yet :-) I had to enforce them for Clapper, in order to avoid a situation where floating mode (PiP) video has only top corners rounded. It would look weird like that.

That's really shocking, LOL, I thought every app with rounded corners in Gnome 40 was a GTK4 app. 

> Actually, since the GTK4 version in Clapper is a debug build it has one GTK4 application that is not part of Clapper. Its GTK Inspector (used for debugging). You can try it if you want see a non-clapper app without installing anything.

Yeah, it is probably related to flatpak then, I've got unhinted text on GTK Inspector too. Sorry to bother you with this, and thanks for the help. I've got an error message when running the debug command, btw, but it is probably unrelated:
`MESA-INTEL: warning: Performance support disabled, consider systctl dev.i915.perf_stream_paranoid=0`

**Comment by Rafostar** [comment] 2021-04-07 15:14
I see that people are also reporting similar issues in GTK gitlab:
[https://gitlab.gnome.org/GNOME/gtk/-/issues/3838](https://gitlab.gnome.org/GNOME/gtk/-/issues/3838)

There was also a workaround merged recently for GTK4:
[https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3407](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3407)

The problem should automatically go away in a few updates of `gsettings-desktop-schemas` and `gtk4`. Nothing I can do here about it, so closing. Just keep your system up-to-date and wait for `gtk4` update in Flatpak container.

**Closed by Rafostar** 2021-04-07 15:14 UTC
Labels: not my bug

**Comment by thegarlynch** [comment] 2021-04-12 14:03
I also found out not only the text jagged but application bar is dissappeared. is this from gtk too ? 

![Screenshot from 2021-04-12 21-02-32](https://user-images.githubusercontent.com/36429132/114407304-c9075500-9b97-11eb-9c49-264b4d7ec2fd.png)
