### ISSUE TITLE
Still running in background? (mounted drive is still busy)

### ISSUE THREAD

**Issue by Crono23** [Rafostar/clapper#207] opened 2022-01-18 14:30 UTC
If I play a video from a mounted drive, close the video, and try to unmount the drive; it will tell me that the drive is still busy. But system monitor shows the app is closed, and running it from terminal also doesn't show anything else.

**Comment by Rafostar** [comment] 2022-01-18 15:12
Duplicate of #205

**Comment by Rafostar** [comment] 2022-01-18 15:14
There is an upstream flatpak portal issue linked in that issue above. If you feel like this is something different, feel free to reopen.

**Closed by Rafostar** 2022-01-18 15:14 UTC

**Comment by Crono23** [comment] 2022-01-18 15:20
I just tried using Flatpak version of Totem to replicate the same result, but Totem doesn't seem to have that issue. Is there a fundamental difference between Clapper and Totem that might cause this?

**Comment by Rafostar** [comment] 2022-01-18 15:43
It gives full access to `/run/media` in order make DVD playback work. This probably causes the `xdg-document-portal` to not be used and thus do not run into that bug.

Try as workaround:
```sh
flatpak override com.github.rafostar.Clapper --filesystem=/run/media
```

**Comment by Crono23** [comment] 2022-01-18 18:38
Tried it but still got the same result, thanks though.

**Comment by Rafostar** [comment] 2022-01-18 19:13
> Tried it but still got the same result, thanks though.

You might need to use `--user` option for flatpak if package was installed for user and not system. Also after applying kill `xdg-document-portal` process if it was started earlier. This workaround works fine on my system.

**Comment by Crono23** [comment] 2022-01-18 20:11
I killd `xdg-document-portal` but I still have the problem. Turns out that workaround was working for physical hard drive, I just tried it. But virtual drive such as encrypted vault still got the same problem. Do you have an idea for those kind of drive? Those are mounted using fuse I think, but I don't understand the detail.

**Comment by Rafostar** [comment] 2022-01-19 09:39
Those kind of questions (and your findings) should be addressed to the `xdg-document-portal` maintainers. That's where bug is, and they should have the best knowledge of their own code.
