### ISSUE TITLE
Corner radius still GTK3

### ISSUE THREAD

**Issue by M00NJ** [Rafostar/clapper#387] opened 2023-11-09 18:29 UTC
Just noticed that Clapper's corner radius is smaller then other GTK4 applications. I think it's still the GTK3 default. Here's a comparison to Gnome Software (Clapper is in the front): 
![Screenshot from 2023-11-09 19-20-59](https://github.com/Rafostar/clapper/assets/82398591/ce52a93e-f0fa-44fd-803e-6c7900f129a4)

**Comment by Rafostar** [comment] 2023-11-09 18:30
Duplicate of #284

**Closed by Rafostar** 2023-11-09 18:30 UTC

**Comment by M00NJ** [comment] 2023-11-09 18:33
Sorry for that. I was searching for other Issues but must have missed it.
