### ISSUE TITLE
Clapper prefers NVDEC over using VAAPI

### ISSUE THREAD

**Issue by ThracianKnight1907** [Rafostar/clapper#388] opened 2023-11-20 15:24 UTC
Hello,

Clapper version 0.5.2 from Flathub seems to be using the nvh264dec instead of the intel gpu. Firefox doesn't seem to have this issue and is using the igpu with vaapi. I also checked this with intel_gpu_top and Clapper doesn't use the intel hardware decoder.

My laptop has an intel uhd 630 + nvidia gtx 1050 ti, and is using the igpu by default. I am running Fedora 39 with Gnome 45.1 and wayland. I am using the intel media driver.

**Comment by Rafostar** [comment] 2023-11-20 16:06
`nvh264dec` is an Nvidia HW accelerated decoder with NVDEC. Currently we default to Nvidia over VAAPI (see #298). This can be changed in preferences by giving a higher rank (like 300) to decoders under `VA` category.

**Comment by Rafostar** [comment] 2023-11-25 09:46
Duplicate of #298

**Closed by Rafostar** 2023-11-25 09:46 UTC
