### ISSUE TITLE
Show incresed Volume value on screen

### ISSUE THREAD

**Issue by Adithyan007hack** [Rafostar/clapper#230] opened 2022-03-14 15:54 UTC
Is there a way to show how much the volume is increased by mouse scrolling on the edge of the screen 

like this :
![Screenshot_2022-03-14_21-19-07](https://user-images.githubusercontent.com/87800041/158210565-3a365754-441e-4850-9b91-18bbc9f7c86b.jpeg)

**Comment by Rafostar** [comment] 2022-03-14 16:42
> Is there a way to show how much the volume is increased

Not yet. We should also show other things besides volume. For this, there is already an open issue, so marking this as duplicate.

Duplicate of #85

**Closed by Rafostar** 2022-03-14 16:42 UTC

**Comment by Adithyan007hack** [comment] 2022-03-15 13:31
Can I expect this feature in future releases?
