### ISSUE TITLE
end of life org.gnome.Platform branch 43

### ISSUE THREAD

**Issue by morfyum** [Rafostar/clapper#383] opened 2023-10-19 14:35 UTC
Hello! 

Can we ask `org.gnome.Platform` update please?

This is the best Gnome video player! 
The only player what can play videos well, and handle subtitles and languages.

```
Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.rafostar.Clapper 
```

**Comment by Ferenc-** [comment] 2023-10-19 15:04
Duplicate of https://github.com/Rafostar/clapper/issues/381 and https://github.com/flathub/com.github.rafostar.Clapper/issues/21.
Please see https://github.com/Rafostar/clapper/pull/344.

**Closed** 2023-11-14 17:43 UTC
