### ISSUE TITLE
Unable to play HEVC - vaapidecode error

### ISSUE THREAD

**Issue by Urworstnit3m3r** [Rafostar/clapper#24] opened 2020-12-06 00:27 UTC
I do not know how feasible it is to get H.265 decoding support due to the license but at the moment Clapper can not play HEVC files while Totem and VLC are able to.

**Comment by Rafostar** [comment] 2020-12-06 13:03
Hi,
Clapper Flatpak should be able to play H.265 as it includes both available GStreamer decoding plugins (`avdec_h265` and hardware accelerated `vaapih265dec`). The third (and probably the fastest) `vah265dec` will be added later on.

* What GPU do you have?
* Wayland or Xorg?
* What happens when you try to play HEVC video (nothing, crash or something else)?
* If you start the app from terminal with:
```sh
flatpak run com.github.rafostar.Clapper
```
do you get any errors printed when you try to open H.265 file?

**Comment by Urworstnit3m3r** [comment] 2020-12-06 15:08
- What GPU do you have? **5700 xt**
- Wayland or Xorg? **Wayland, running all mesa drivers**
- What happens when you try to play HEVC video (nothing, crash or something else)? **When you attempt to open it the player opens, but then just sits at a black screen with no sound and also only shows 00:00/00:00 for the time.**
- If you start the app from terminal with: **No errors show up in the terminal.**

![Untitled](https://user-images.githubusercontent.com/37315608/101283785-567a0900-37a2-11eb-8942-aab40a161626.png)

**Comment by Rafostar** [comment] 2020-12-06 16:16
Since the app does not print any errors, it seems like `GStreamer` issue. I cannot reproduce as it works with H.265 on my side, so lets check if `GStreamer` gives you any errors/warnings when you load video:
```
GST_DEBUG=3 flatpak run com.github.rafostar.Clapper
```

**Comment by Urworstnit3m3r** [comment] 2020-12-06 16:32
`GST_DEBUG=3 flatpak run com.github.rafostar.Clapper

0:00:06.373689947     2 0x559955e1ed20 WARN                 basesrc gstbasesrc.c:3688:gst_base_src_start_complete:<source> pad not activated yet

0:00:06.373947535     2 0x559955e1ed20 WARN                 basesrc gstbasesrc.c:3688:gst_base_src_start_complete:<source> pad not activated yet

0:00:06.379562553     2 0x559955d94d20 FIXME          matroskademux matroska-demux.c:667:gst_matroska_demux_parse_colour:<matroskademux0> Unsupported subelement 0x55b7 in Colour

0:00:06.379577662     2 0x559955d94d20 FIXME          matroskademux matroska-demux.c:667:gst_matroska_demux_parse_colour:<matroskademux0> Unsupported subelement 0x55b8 in Colour

0:00:06.418879460     2 0x559955d94d20 WARN              vaapiblend gstvaapiblend.c:184:gst_vaapi_blend_initialize:<vaapiblend0> VPP does not support global alpha blending

0:00:06.486524134     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xf0 - ignoring

0:00:06.486541968     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xf0 - ignoring

0:00:06.486548420     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xb2 - ignoring

0:00:06.486554542     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xf0 - ignoring

0:00:06.486560002     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xb2 - ignoring

0:00:06.486565052     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xf0 - ignoring

(...) bunch of same error

0:00:06.486569821     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xb2 - ignoring

0:00:06.486574580     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xf0 - ignoring

0:00:06.486579309     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xb2 - ignoring

0:00:06.486584158     2 0x559955d94d20 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux0:sink> Unknown CueTrackPositions subelement 0xf0 - ignoring

0:00:06.682568944     2 0x559955d94d20 FIXME          matroskademux matroska-demux.c:667:gst_matroska_demux_parse_colour:<matroskademux0> Unsupported subelement 0x55b7 in Colour

0:00:06.682578362     2 0x559955d94d20 FIXME          matroskademux matroska-demux.c:667:gst_matroska_demux_parse_colour:<matroskademux0> Unsupported subelement 0x55b8 in Colour

0:00:06.687548106     2 0x7fc2bc002b00 WARN             vaapidecode gstvaapidecode.c:780:gst_vaapidecode_handle_frame:<vaapidecode0> decode error -1

(...) bunch of same error

0:00:06.905261526     2 0x7fc2bc002b00 WARN            videodecoder gstvideodecoder.c:4346:_gst_video_decoder_error:<vaapidecode0> error: Decoding error

0:00:06.905266996     2 0x7fc2bc002b00 WARN            videodecoder gstvideodecoder.c:4348:_gst_video_decoder_error:<vaapidecode0> error: Decode error -1

0:00:06.905282145     2 0x7fc2bc002b00 WARN            videodecoder gstvideodecoder.c:2909:gst_video_decoder_prepare_finish_frame:<vaapidecode0> decreasing timestamp (0:00:52.991000000 < 0:00:53.116000000)

0:00:06.905379390     2 0x7fc2bc002b00 WARN             vaapidecode gstvaapidecode.c:780:gst_vaapidecode_handle_frame:<vaapidecode0> decode error -1

0:00:06.905389328     2 0x7fc2bc002b00 WARN            videodecoder gstvideodecoder.c:4346:_gst_video_decoder_error:<vaapidecode0> error: Decoding error

0:00:06.905395049     2 0x7fc2bc002b00 WARN            videodecoder gstvideodecoder.c:4348:_gst_video_decoder_error:<vaapidecode0> error: Decode error -1

0:00:06.905413584     2 0x7fc2bc002b00 WARN            videodecoder gstvideodecoder.c:2909:gst_video_decoder_prepare_finish_frame:<vaapidecode0> decreasing timestamp (0:00:53.074000000 < 0:00:53.116000000)
`
![image](https://user-images.githubusercontent.com/37315608/101286098-49631700-37ae-11eb-81e6-f1b3f2128845.png)

**Comment by Rafostar** [comment] 2020-12-06 18:08
> Not sure if the system packages matter since this is a flatpak

Since this is a flatpak all plugins are included inside. System packages are not used.

```sh
vaapidecode gstvaapidecode.c:780:gst_vaapidecode_handle_frame:<vaapidecode0> decode error -1
```

This is clearly a `GStreamer` VAAPI error. Does this happen for every HEVC video you have or only this one?

**Comment by Urworstnit3m3r** [comment] 2020-12-06 18:16
I tested with 5 different videos all had the error. One with DTS audio also gave these errors and Clapper crashed.

```
0:00:22.542652744     2 0x7f24b8035a40 WARN      matroskareadcommon matroska-read-common.c:711:gst_matroska_read_common_parse_skip:<matroskademux1:sink> Unknown CueTrackPositions subelement 0xf0 - ignoring
0:00:22.549141496     2 0x7f24c0013180 WARN                    alsa conf.c:5200:snd_config_expand: alsalib error: Unknown parameters {AES0 0x02 AES1 0x82 AES2 0x00 AES3 0x02}
0:00:22.549156223     2 0x7f24c0013180 WARN                    alsa pcm.c:2660:snd_pcm_open_noupdate: alsalib error: Unknown PCM default:{AES0 0x02 AES1 0x82 AES2 0x00 AES3 0x02}
0:00:22.553266395     2 0x7f24c0013060 WARN            uridecodebin gsturidecodebin.c:957:unknown_type_cb:<uridecodebin0> warning: No decoder available for type 'audio/x-dts, framed=(boolean)true, rate=(int)48000, channels=(int)6, endianness=(int)4321, depth=(int)16, block-size=(int)512, frame-size=(int)2012'.
```

**Comment by Rafostar** [comment] 2020-12-06 18:24
> I tested with 5 different videos all had the error.

OK. Since you reported this as a HEVC issue and you use Wayland, I assume that H.264 videos are working for you and you are using `vah264dec` plugin enabled in player advanced prefs (and have not too high CPU usage with those), right?

**Comment by Urworstnit3m3r** [comment] 2020-12-06 18:33
H.264 video's do work, I am not using the vah264dec plugin.
I would say cpu usage is low.
![Untitled](https://user-images.githubusercontent.com/37315608/101288994-21c87a80-37bf-11eb-8b2b-665a5d9561c6.png)

**Comment by Rafostar** [comment] 2020-12-06 18:43
If you are on Wayland, than please enable `vah264dec` plugin and restart player and check again your CPU usage. I know that you want HEVC but checking if (and how) `vah264dec` works for you is important to get HEVC working.

**Comment by Urworstnit3m3r** [comment] 2020-12-06 18:49
Okay, I did enable it and tried again, seems to have dropped by ~6% when playing same H.264 as above. H.265 version no change.

![Untitled](https://user-images.githubusercontent.com/37315608/101289329-5ccbad80-37c1-11eb-9c1b-359e509e93a5.png)

**Comment by Rafostar** [comment] 2020-12-06 19:02
> Okay, I did enable it and tried again, seems to have dropped by ~6% when playing same H.264 as above. H.265 version no change.

Thanks. `vah264dec` is a brand new and experimental H.264 plugin that should give better performance for H.264 videos and I really appreciate all testing of it under Wayland. Let me check a few things and I will contact you regarding hevc support later.

As for DTS, I have opened a separate issue here #25 cause this one plugin is indeed missing from Flatpak package.

**Comment by Rafostar** [comment] 2020-12-07 16:00
@Urworstnit3m3r 

Here is the sum up of HEVC decoding situation:

GStreamer developers are recently working on a new and better VA-API decoding plugins. What is called a `va` series. They should work faster (and hopefully be more reliable) then the older `gstreamer-vaapi` plugins. Right now in latest release 1.18 only `vah264dec` was added. And we confirmed that it is working in your setup :smile:. Next `GStreamer` release (early-alpha scheduled for `17.12.2020`) should include additionally `vah265dec` (for HEVC) and `vavp9dec` (for VP9), but they are "work in progress" so might not be as good/usable as `vah264dec` yet.

If you want help getting hardware accelerated HEVC decoding with the current VA-API plugin, then please open it as an issue on [gstreamer-vaapi gitlab](https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi). Since this is their part that fails and not mine, they should be able to provide better support and do an eventual fix for you. Obviously they have no idea what a "Clapper" is, so you can tell them that `vaapidecode` fails on HEVC videos for you and that you are using `GstPlayer` powered media player with GStreamer 1.18.1. And send them the log output when started with `GST_DEBUG=4` (increase value to `4` or maybe even `5` to get a little more info for them).

For the time being you can go to `Clapper` Advanced settings tab and in `GStreamer Plugin Ranking` leave `vah264dec` applied and additionally add `vaapidecodebin` and `vaapih265dec` both with rank `0` (zero) and check-mark apply them. This should disable old `gstreamer-vaapi` plugins and make the player fallback into using FFmpeg-based plugins for HEVC playback (the same as what Totem uses).

**Comment by Rafostar** [comment] 2021-01-09 11:49
Relevant `mesa` fix that needs to be merged:
[https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7949](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7949)

Additionally GStreamer 1.19 is still needed for high performance `vah265dec` decoder. It was supposed to be released by the end of the year, but got delayed due to some unexpected bugs and holiday season.

**Comment by Rafostar** [comment] 2021-01-22 16:13
Fix landed in `mesa` git master. Nothing more to do here, only wait for next `mesa` update that will have it (probably ver 21.1) or impatient users can compile `mesa` themself.

**Closed by Rafostar** 2021-01-22 16:13 UTC
Labels: GStreamer
