### ISSUE TITLE
Recalculate End Time on changing playback speed

### ISSUE THREAD

**Issue by amit9838** [Rafostar/clapper#337] opened 2023-01-24 07:04 UTC
**Current Behaviour**
End time stays same,  whatever playback speed is.

**Expected Behaviour**
It must be recalculated according to playback speed.
like if I speedup the video to 2x then end time should decrese to half.

**Comment by Rafostar** [comment] 2023-01-24 13:56
Duplicate of #225

**Closed by Rafostar** 2023-01-24 13:56 UTC
