### ISSUE TITLE
Bug: Doesn't respect orientation

### ISSUE THREAD

**Issue by forteller** [Rafostar/clapper#353] opened 2023-04-30 19:15 UTC
I just played a video recorded on my phone in Clapper, VLC, Gnome Video and Celluloid, and Clapper was the only one that didn't get the orientation right. It played it laying down, even though the video was taken upright. 

Let me know if you need any more info from me.

Thanks for your work! :)

**Comment by Rafostar** [comment] 2023-04-30 20:26
Not a "Bug" per-se, as this is simply not implemented yet. Someone kind enough submitted a MR that adds this "functionality". It will be merged soon. See #349

Also, since there was already an issue about this earlier, I will mark this as duplicate to avoid having same issues multiple times.

**Comment by Rafostar** [comment] 2023-04-30 20:27
Duplicate of #310

**Closed by Rafostar** 2023-04-30 20:27 UTC
