### ISSUE TITLE
no icons

### ISSUE THREAD

**Issue by titi8530** [Rafostar/clapper#22] opened 2020-11-30 13:32 UTC
Icons on headerbar ( floating mode et fullscreen) and others not here. Nice work :)

**Comment by Rafostar** [comment] 2020-11-30 13:39
Duplicate of #9 

Try changing icon theme to Adwaita.

**Comment by titi8530** [comment] 2020-11-30 13:56
It's OK with Adwaita. Thanks. Beautiful player.

**Comment by Rafostar** [comment] 2020-11-30 15:57
> Edit: no progess bar with webm videos.

Player is a "work in progress". Many features not implemented yet. This is unrelated to icons. If you want me to look into it, open a separate issue and provide an example file that does not work for you.

**Closed by Rafostar** 2020-11-30 15:57 UTC
