### ISSUE TITLE
[Feature request] Resize window to fit media by default

### ISSUE THREAD

**Issue by kdwk** [Rafostar/clapper#213] opened 2022-02-09 04:57 UTC
Resizing Clapper windows to the height and width of the media being played by default prevents black bars around the media from being visible and ensures efficient use of screen space. 

### Prior Art

![loop-video-mac-quicktime-player](https://user-images.githubusercontent.com/39268094/153124696-564e1abe-c1b8-4787-8cac-3f0bb5f7ad55.jpg)
_QuickTime Player automatically resizes the window to the height and width of the media being played_

**Comment by Rafostar** [comment] 2022-02-09 07:25
Duplicate of #30

**Closed by Rafostar** 2022-02-09 07:25 UTC
