### ISSUE TITLE
Dark mode not working (gtk-application-prefer-dark-theme with libadwaita is unsupported)

### ISSUE THREAD

**Issue by Midar** [Rafostar/clapper#184] opened 2021-11-19 13:27 UTC
I'm getting this on the console when trying to use dark mode (also having system-wide dark mode in GNOME by setting the theme to Adwaita Dark):

```
(com.github.rafostar.Clapper:15390): Adwaita-WARNING **: 14:15:21.534: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
```

I realize that libadwaita no longer wants themeing and instead wants a color scheme. I checked my Gtk config and remove gtk-application-prefer-dark-theme, but the issue remains, so it seems to be with the way Clapper requests dark mode.

Installed libadwawita is 0.6.alpha.4.fc35. Package being used is https://bodhi.fedoraproject.org/updates/FEDORA-2021-d0ac0f825b.

**Comment by Rafostar** [comment] 2021-11-19 14:23
> Installed libadwawita is 0.6.alpha.4.fc35. Package being used is https://bodhi.fedoraproject.org/updates/FEDORA-2021-d0ac0f825b.

I did not know that there were any other Fedora RPM packages then the one build on opensuse build system. Interesting.

> I realize that libadwaita no longer wants themeing and instead wants a color scheme.

No, that's unrelated here. The problem is that libadwaita is not stable and does not promise API stability yet, thus Clapper is constantly getting broken one way or another. Current code was written against `libadwaita-alpha.2` release. I am gonna recommend using Flatpak Clapper package for the time being which I personally maintain, thus have control over deps and their versions that are being included.

Anyway, this peculiar issue was fixed on Clapper git yesterday, so closing.

**Closed by Rafostar** 2021-11-19 14:23 UTC

**Comment by Midar** [comment] 2021-11-19 14:28
Sorry, should have checked commits first. I'll backport https://github.com/Rafostar/clapper/commit/d2df1c3bd8229474005d2300808895244def0e8e and include it in the Fedora package.

**Comment by Rafostar** [comment] 2021-11-19 14:37
> Sorry, should have checked commits first. I'll backport [d2df1c3](https://github.com/Rafostar/clapper/commit/d2df1c3bd8229474005d2300808895244def0e8e) and include it in the Fedora package.

This is not the only issue alpha3+ introduced. There are also some theming bugs/problems. There will likely be a Clapper 0.4.1 bugfix release to fix most of these and other issues in near future.

BTW: I also received notification from your comment regarding yt-dlp support, but for some reason it does not appear on github issue comments for me.

**Comment by Midar** [comment] 2021-11-19 14:42
How long is 0.4.1 out? If this is just a week or so, then I won't bother backporting, but if it's a month, I'd rather backport at least the most significant fixes.

**Comment by Midar** [comment] 2021-11-19 14:50
Looking at all commits since 0.4.0, this seems to be the only libadwaita-releated fix so far. I'll go ahead and include it in the package, since that can't hurt (local testing worked well) and of course update to 0.4.1 once it's out.

**Comment by Rafostar** [comment] 2021-11-19 14:56
I hope it will be out within next week or two, but considering I am the only person that works on this project I cannot promise any ETA. Not everything is fixed yet. Thanks for the fedora package BTW. If you have any questions or things to discuss feel free to ask (preferably on [#clapper-player](https://matrix.to/#/#clapper-player:matrix.org) matrix channel :smiley: ).
