### ISSUE TITLE
put the "finish" time back in clapper 6

### ISSUE THREAD

**Issue by legacychimera247** [Rafostar/clapper#455] opened 2024-06-05 21:42 UTC
one thing i loved about clapper was the fact it showed the hour the video finished, at least in 5.2

i also proposed this for totem cause i find it damn useful (it got refused of course, as totem is not a time application)

now i see it's gone in clapper 6, would it be nice to have it back

**Comment by Rafostar** [comment] 2024-06-06 07:07
Duplicate of #424

**Closed by Rafostar** 2024-06-06 07:07 UTC
